INSERT INTO region (norg) VALUES 
('AGNEBY-TIASSA'),('BAFING'),('BAGOUE'),('BELIER'),('BERE'),('BOUNKANI'),('CAVALLY'),('DITRICT AUTONOME D’ABIDJAN'),
('DISTRICT AUTONOME DE YAMOUSSOUKRO'),('FOLON'),('GBEKE'),('GBOKLE'),('GOH'),('GONTOUGO'),('GRANDS PONTS'),('GUEMON'),
('HAMBOL'),('HAUT SASSANDRA'),('IFFOU'),('INDENIE-GJUABLIN'),('KABADOUGOU'),('LOH-DJIBOUA'),('MARAHOUE'),('ME'),
('MORONOU'),('NAWA'),('N’ZI'),('PORO'),('SAN PEDRO'),('SUD COMOE'),('TCHOLOGO'),('TONKPI'),('WORODOUGOU');